### ISSUE TITLE
Chapter 4. 카프카 프로듀서

### ISSUE THREAD

**Issue by kmg28801** [kmg28801/kafka-study#4]

**Comment by Genie-young** [comment]
# chapter 4. 카프카 프로듀서

- 프로듀서 : 메세지를 생산해서 카프카의 토픽으로 메세지를 보내는 역할을 하는 애플리케이션, 서버 등

- 주요 역할

  1. 메시지를 토픽 파티션에 매핑

  2. 파티션의 리더에 요청을 보냄

  3. 키값을 정해 해당 키를 가진 모든 메시지를 동일한 파티션으로 전송

     키값 미지정 시, 라운드 로빈 방식으로 파티션에 균등 배분

## 4.1 콘솔 프로듀서로 메시지를 보내는 방법

```cmd
#존재하지 않는 토픽으로 메시지 전송 시 자동 토픽 생성
auto.create.topics.enable = true

#kafka-topics.sh
##토픽 생성하기
# /usr/local/kafka/bin/kafka-topic.sh 토픽 관련 기능이 들어있는 쉘파일
# --zookeeper: 주키퍼 리스트, --topic: 토픽명, --replication-factor: 복제 갯수
#zookeeper 리스트를 server.properties와 동일하게 맞춰주지 않으면 토픽 생성 에러남 *참고1
/usr/local/kafka/bin/kafka-topics.sh \
--zookeeper peter-zk001:2181,peter-zk002:2181,peter-zk003:2181/peter-kafka \
--topic peter-topic --partitions 1 --replication-factor 3 --create
```

![image-20230430232357240](C:\Users\뚜이\AppData\Roaming\Typora\typora-user-images\image-20230430232357240.png)

```cmd
##토픽 정보 확인하기
/usr/local/kafka/bin/kafka-topics.sh \
--zookeeper peter-zk001:2181/peter-kafka --topic peter-topic --describe
```

![image-20230430232338538](C:\Users\뚜이\AppData\Roaming\Typora\typora-user-images\image-20230430232338538.png)

PartitionCount(파티션 개수) : 1개, ReplicationFactor(복제수) : 3개, Topic(토픽명) : peter-topic , Partition(파티션):0번 파티션, Leader : 3번, Replica(복제 중인 broker) : 3,1,2, isr(ISR 위치) : 3,1,2


```cmd
#kafka-console-producer.sh
##카프카 토픽으로 테스트 메시지 전송하기 
## broker 
# /usr/local/kafka/bin/kafka-console-producer.sh 프로튜서 관련 기능이 들어있는 쉘파일
# --broker-list: 메세지를 받을 브로커 목록, --topic:메세지를 받을 토픽, --compression-codec : 압축 포맷, request-required-acks:회신 수, 뒷장에 더 설명있음. 
/usr/local/kafka/bin/kafka-console-producer.sh \
--broker-list peter-kafka001:9092,peter-kafka002:9092,peter-kafka003:9092 \
--topic peter-topic
#명령 실행 후 입력창이 나오면 카프카에 보낼 메세지 작성하고 엔터, 중단하고 싶으면 Ctrl+C

/usr/local/kafka/bin/kafka-console-producer.sh \
--broker-list peter-kafka001:9092,peter-kafka002:9092,peter-kafka003:9092 \
--topic peter-topic --compression-codec 'gzip' --request-required-acks 1
```

![image-20230430234112062](C:\Users\뚜이\AppData\Roaming\Typora\typora-user-images\image-20230430234112062.png)

```cmd
#kafka-console-consumer.sh
##카프카로 들어온 메세지 확인하기
/usr/local/kafka/bin/kafka-console-consumer.sh \
--bootstrap-server peter-kafka001:9092,peter-kafka002:9092,peter-kafka003:9092 \
--topic peter-topic --from-beginning
```

![image-20230430234121663](C:\Users\뚜이\AppData\Roaming\Typora\typora-user-images\image-20230430234121663.png)

## 4.2 자바와 파이썬을 이용한 프로듀서

카프카는 스칼라 기반, 메인 클라이언트 라이버러리는 자바로 만들어진 어플리케이션. 
가장 많은 기능을 제공하는 자바 및 파이썬으로 실습 진행.
send()로 보내는 방식은 3가지(메세지를 보내고 미확인, 동기 전송, 비동기 전송)

jdk 설치 및 kafka-clients-2.5.0.jar, slf4j-api-2.0.7.jar 만 로드하여 cmd로 자바 코드 실행함. 

```java
/*파일명 : KafkaBookProducer1.java */
import org.apache.kafka.clients.producer.KafkaProducer;
import org.apache.kafka.clients.producer.Producer;
import org.apache.kafka.clients.producer.ProducerRecord;

import java.util.Properties;

public class KafkaBookProducer1 {
  public static void main(String[] args) {
    Properties props = new Properties();
    props.put("bootstrap.servers", "localhost:9092,localhost:9093,localhost:9094");
    props.put("key.serializer", "org.apache.kafka.common.serialization.StringSerializer");
    props.put("value.serializer", "org.apache.kafka.common.serialization.StringSerializer");

    Producer<String, String> producer = new KafkaProducer<>(props);
	/* send() 메소드로 ProducerRecord를 보냄. 
     메시지는 버퍼에 저장되고 별도의 스레드를 통해 브로커로 전송함. */
    producer.send(new ProducerRecord<String, String>("peter-topic", "Apache Kafka is a distributed streaming platform"));
    producer.close();
  }
}
```

```cmd
javac -cp "외부 라이브러리 경로" KafkaBookProducer1.java
java  -cp "외부 라이브러리 경로"; KafkaBookProducer1 
```

![image-20230501002116073](C:\Users\뚜이\AppData\Roaming\Typora\typora-user-images\image-20230501002116073.png)

![image-20230501002145016](C:\Users\뚜이\AppData\Roaming\Typora\typora-user-images\image-20230501002145016.png)

```java
./*프로듀서에 추가 옵선 적용*/
import org.apache.kafka.clients.producer.KafkaProducer;
import org.apache.kafka.clients.producer.Producer;
import org.apache.kafka.clients.producer.ProducerRecord;

import java.util.Properties;

public class KafkaBookProducer1 {
  public static void main(String[] args) {
    Properties props = new Properties();
    props.put("bootstrap.servers", "localhost:9092,localhost:9093,localhost:9094");
    props.put("acks", "1");
    props.put("compression.type", "gzip");
    props.put("key.serializer", "org.apache.kafka.common.serialization.StringSerializer");
    props.put("value.serializer", "org.apache.kafka.common.serialization.StringSerializer");

    Producer<String, String> producer = new KafkaProducer<>(props);
    producer.send(new ProducerRecord<String, String>("peter-topic", "Apache Kafka is a distributed streaming platform"));
    producer.close();
  }
}
```



### 4.2.1 메시지를 보내고 확인하지 않기

카프카가 살아있는 상태에서 프로듀서에서 에러가 났다면 재전송하기 때문에 대부분 성공적으로 전송되지만 일부 메시지는 손실될 수 있다.
메시지 손실 각능성이 있기 때문에 일반적인 서비스 환경에서는 사용하지 않는다.

```java
/*메시지를 보내고 확인하지 않기 */
/*KafkaBookProducer1.java 코드와 비교해 프로듀서에서 에러가 나는 경우의 예외 처리를 추가함.
 해당 예제 코드에서는 에러가 날 경우 재전송에 대한 코드없이 단순 에러 출력하고 종료함.
 재전송하려면 추가 코드 작성이 필요.*/
Producer<String, String> producer = new KafkaProducer<>(props);
try{
    /* 결과객체를 받아오지 않아 성공적으로 전송했는 지 여부는 알 수 없음. */
    producer.send(new ProducerRecord<String, String>("peter-topic", "Apache Kafka is a distributed streaming platform"));
}catch(Exception){
    /*프로듀서에서 보내는 도중 에러가 날 경우의 에러 출력*/
    exception.printStackTrace();
}finally{
    /* 연결 종료 */
    producer.close();
}
```

 

### 4.2.2 동기 전송

```java
/*동기전송 */
/*프로듀서는 메시지를 send()메소드는 Future 객체를 반환하고, Future 객체의 get()메소드를 통해 RecordMetadata의 정보를 가져와서 성공 여부 확인*/
Producer<String, String> producer = new KafkaProducer<>(props);
try{
    /*결과값을 받아 객체에 저장, get으로 객체를 가지고 올때까지 기다림. */
    RecordMetadata metadata = producer.send(new ProducerRecord<String, String>("peter-topic", "Apache Kafka is a distributed streaming platform")).get();
    /*메시지가 저장된 파티션 정보 및 위치를 받아서 출력.*/
    System.out.printf("Partition:%d, Offset:%d", metadata.partition(), metadata.offset())
}catch(Exception){
    /*예외 처리 시 재시도 가능한 예외와 재시도 불가능 예외가 발생할 수 있음. 
      재시도 가능한 예외 : 다시 전송하여 해결 ex) 커넥션 에러
      재시도 불가능한 예외 ex) 메시지 최대 크기 초과*/
    exception.printStackTrace();
}finally{
    producer.close();
}
```

### 4.2.3 비동기 전송 

```java
/* 비동기전송, 파일명 : PeterCallback.java */
/*org.apache.kafka.clients.producer.Callback 구현 클래스 필요
  메세지 보낼 때 콜백을 호출하고, 카프카 브로커에서 응답을 받으면 콜백함.
  응답을 기다리지 않기 때문에 빠른 전송이 가능함. 
  메시지 미전송 시 예외 처리로 에러 기록을 하여 향후 처리 가능함.*/
import org.apache.kafka.clients.producer.Callback
    
class PeterCallback implements Callback{
    /*오류 리턴 시, onCompletion 예외를 갖게 됨. */
    public void onConmpletion(RecorMetadat metadata, Exception exception){
        if(metadata !=null ){
            System.out.println("Partition : " + metadata.partition() + ", Offset:" +  metadata.offset() + "");
        }else{
            exception.printStackTrace();
        }
    }
}
```



```java
/*비동기전송, 파일명 : KafkaBookProducer3.java*/

Producer<String, String> producer = new KafkaProducer<>(props);
try{
    /* 프로듀서에 레코드 전송 시, 콜백 오브젝트를 같이 보냄. */
    RecordMetadata metadata = producer.send(new ProducerRecord<String, String>("peter-topic", "Apache Kafka is a distributed streaming platform"),new PeterCallback());
}catch(Exception){
    exception.printStackTrace();
}finally{
    producer.close();
}
```

### 파이썬

kafka-python 라이브러리가 이용자 수가 많고, confluent-kafka-python이 성능이 좋음.
confluent-kafka-python 사용을 위해서는 librdkafka(아파티 카프카 프로토콜의 C 라이브러리) 설치 필요
책은 kafka-python 사용

```python
from kafka import KafkaProducer

#메세지 전송을 위해 broker list 지정
#broker list를 다 지정하지 않은 경우, 지정한 호스트가 다운되면 오류 발생함.
#다 지정하면 한 개의 호스트가 다운되도 다른 호스트에 메시지 전달.
producer = KafkaProducer(bootstrap_servers='peter-kafka001:9092,peter-kafka002:9092,peter-kafka003:9092')

#메시지 내용 적고 전송 
producer.send('peter-topic', 'Apache Kafka is a distributed streaming platform')
```

```py
#추가 옵션 지정
from kafka import KafkaProducer

producer = KafkaProducer(acks=1, compression_type='gzip', bootstrap_servers='peter-kafka001:9092,peter-kafka002:9092,peter-kafka003:9092')

producer.send('peter-topic', 'Apache Kafka is a distributed streaming platform')
```



## 4.3 프로듀서 활용 예제

- loop 문을 사용해서 여러 번 전송 가능. 

- key 옵션으로 지정한 파티션에만 메시지 보낼 수 있음. 해당 옵션이 없을 경우 라운드 로빈 방식으로 균등 배분

```cmd
#파티션이 2개인 토픽 생성하기(peter-topic2)
C:\Kafka\kafka001\bin\windows\kafka-topics.bat --create --zookeeper localhost:2181,localhost:2182,localhost:2183/peter-kafka --replication-factor 1 --partitions 2 --topic peter-topic2
```

```java
/* loop 사용 + key 지정하기 */
import org.apache.kafka.clients.producer.KafkaProducer;
import org.apache.kafka.clients.producer.Producer;
import org.apache.kafka.clients.producer.ProducerRecord;

import java.util.Properties;

public class KafkaBookProducerKey {
  public static void main(String[] args) {
    Properties props = new Properties();
    props.put("bootstrap.servers", "peter-kafka001:9092,peter-kafka002:9092,peter-kafka003:9092");
    props.put("acks", "1");
    props.put("compression.type", "gzip");
    props.put("key.serializer", "org.apache.kafka.common.serialization.StringSerializer");
    props.put("value.serializer", "org.apache.kafka.common.serialization.StringSerializer");

    Producer<String, String> producer = new KafkaProducer<>(props);
    String testTopic = "peter-topic2";
    String oddKey = "1"; 
    String evenKey = "2";

    for (int i = 1; i < 11; i++) {
      if (i % 2 == 1) {
        /*키 지정 후 메시지 전송하기 홀수일 때는 1번 파티션, 짝수는 2번 파티션으로 전송*/
        producer.send(new ProducerRecord<String, String>(testTopic, oddKey, String.format("%d - Apache Kafka is a distributed streaming platform - key=" + oddKey, i)));
      } else {
        producer.send(new ProducerRecord<String, String>(testTopic, evenKey, String.format("%d - Apache Kafka is a distributed streaming platform - key=" + evenKey, i)));
      }
    }
    producer.close();
  }
}
```

![image-20230501012055948](C:\Users\뚜이\AppData\Roaming\Typora\typora-user-images\image-20230501012055948.png)

![image-20230501011956364](C:\Users\뚜이\AppData\Roaming\Typora\typora-user-images\image-20230501011956364.png)

#### 0번 파티션만 가져오기

topic을 생성하지 않고 메시지 전송 시, 카프카 옵션에 따라 토픽이 자동 생성될 수 있다.
이럴 경우 파티션은 1인데, 토픽 삭제 후 재생성하거나, alter 명령어를 이용해 수정한다. *참고 2

```cmd
C:\Kafka\kafka001\bin\windows\kafka-console-consumer.bat --bootstrap-server localhost:9092,localhost:9093,localhost:9094 --topic peter-topic2 --from-beginning --partition 0
C:\Kafka\kafka001\bin\windows\kafka-console-consumer.bat --bootstrap-server localhost:9092,localhost:9093,localhost:9094 --topic peter-topic2 --from-beginning --partition 1
```

![image-20230501013805303](C:\Users\뚜이\AppData\Roaming\Typora\typora-user-images\image-20230501013805303.png)

## 4.4 프로듀서의 주요 옵션 

- bootstrap.servers
  카프카 클러스터는 마스터 클러스터의 개념이 없어, 모든 브로커(서버)가 클라이언트 요청을 받을 수 있음.
  전송 시 broker-list 옵션으로 브로커 정보를 나열하는데, 하나의 호스트만 입력하면 해당 호스트에 장애가 나는 경우 접속이 불가하다.
  따라서 브로커 리스트에는 모든 브로커 정보를 나열하면 하나가 장애가 발생할 경우 다른 서버로 재접속을 시도하여 정상적으로 서비스 받기 때문에, 고가용성을 유지할 수 있다.
- acks
  프로듀서가 카프카 토픽의 리더에게 메시지를 보낸 후 요청을 완료하기 전 ack(승인)의 수.
  옵션의 수가 작으면 성능이 좋지만, 메시지 손실 가능성이 있고, 반대로 수가 크면 성능이 좋지 않지만 메시지 손실 가능성도 줄어들거나 없어짐.
- acks=0
  서버로부터 메시지를 기다리지 않음. 따라서 재설정요청도 안함. 응답을 기다리지 않아 빠르게 메세지를 기다릴 수 있어 높은 처리량을 얻을 수 있음.
- acks=1
  리더는 데이터를 기록하지만, 모든 팔로워는 확인하지 않음. 이 경우 일부 데이터 손실이 발생할 수 있음.
- acks=all 또는 -1
  리더는 ISR의 팔로워로부터 데이터에 대한 ack를 기다림. 하나의 팔로워가 있는 한 데이터는 손실되지 않으며, 데이터 무손실에 대해 가장 강력하게 보장함. 
- buffer.memory
  서버로 데이터를 보내기 위해 잠시 대기(배치 전송이나 딜레이 등) 할 수 있는 전체 메모리 바이트
- compression.type
  데이터 압축 타입 ex) none, gzip, snappy, lz4
- retries
  일시적인 오류로 인해 전송에 실패한 데이터를 다시 보내는 횟수
- batch.size
  성능을 높이기 위해 배치로 여러 데이터를 함께 보냄. 이때 배치 크기 바이트 조정 가능.
  정의된 크기보다 큰 데이터는 배치 시도를 하지 않음.
  배치 보내기 전 클라이언트 장애 발생 시 배치 내의 메시지는 전달되지 않음.
  고가용성이 필요하면 배치 사이즈를 주지 않는 게 좋음.
- linger.ms
  배형태의 메시지를 보내기 전에 추가적인 메시지들을 가디라는 시간
  지정된 배치 사이즈에 도달하면 이 옵션과 관계없이 즉시 전송
  배치 사이즈 도달 못했는데, liner.ms 제한 시간에 도달하면 메시지 전송
  0이 기본값(지연 없음), 0보다 큰 값 설정 시 지연 시간은 조금 발생하지만 처리량은 좋아짐. 
- max.request.size
  최대 메시지 바이트 사이즈, 기본값을 1MB

## 4.5 다양한 메시지 전송 방법

### 4.5.1 메시지 손실 가능성이 높지만 빠른 전송이 필요한 경우

- ack = 0일, 응답을 받지 않음
- 빠른 전송이 가능
- 메시지 손실이 나도 알 수 없다.
- 일반적인 운영상황의 경우 메시지 손실 없이 빠르게 보내지만,브로커가 다운되는 등 장애 상황에는 메시지 손실이 발생할 수 있다. 

### 4.5.2 메시지 손실 가능성이 적고 적당한 속도의 전송이 필요한 경우 

- ack = 1, 파티션의 리더에 저장되면 응답 받음
- 리더 장애시 메시지 유실 가능
- 유실 시나리오 
  리더에 성공적으로 저장 후 성공응답을 받았는데 팔로워에는 아직 복제되지 않았는데 리더에서 장애가 나 리더에만 메시지 저장된 상태  
  팔로워에 복제되지 않은 상태에서 팔로워 중에 하나가 리더가 되면 기존 리더에 저장된 메시지가 유실됨
- 약 8~10회 정도의 테스트 중 단 1회 메시지 손실이 재현됨.
- 운영 환경에서도 프로듀서 옵션을 acks=1를 사용하고 리더 선출 작업 등이 일어났다고 해서 무조건 메시지 손실이 발생하는 것이 아니라 아주 예외적인 경우로 메시지 손실이 발생할 가능성이 있다라고 이해하면 됨.
- 로그스태시, 파일비트 포함 프로듀서 애플리케이션은 보통 acks=1이 기본값인 경우가 많음. 
  속도와 안전성 확보할 수 있는 acks=1 추천.

### 4.5.3 전송 속도는 느리지만 메시지 손실이 없어야 하는 경우

- ack = all 또는 -1

  - 리더 및 팔로워까지 메시지를 받았는 지 확인 
  - 가장 느리지만 메시지 손실을 허용하지 않을 경우 사용
  - 브로커의 server.properties에서 `min.insync.replicas` 설정도 같이함.
  - 엄격하게 전송을 보장해야하는 상황에서 사용

- **리플리카 개수 3, `ack = all`, `min,insync.replicas` = 2**
  리더에 저장하고 팔로워 중 한 개에 저장하면 최소 개수를 충족하기 때문에 성공 응답

- **리플리카 개수 3, `ack = all`, `min,insync.replicas` = 1**
  리더에 저장되면 성공 응답
  `ack = 1`과 동일 (리더 장애시 메시지 유실 가능)

- **리플리카 개수 3, `ack = all`, `min,insync.replicas` = 3**
  리더와 팔로워 2개에 저장되면 성공 응답
  팔로워 중 한 개라도 장애가 나면 리플리카 부족으로 저장에 실패함
  다운된 서버 수는 한 개지만 전체 장애가 될 수 있음. 

  `min,insync.replicas` 옵션은 리플리카 개수와 동일하게 지정하면 안됨
  리플리카 개수 3, `ack = all`, `min,insync.replicas` = 2 권장함.

  

## 참고

1. 카프카 토픽 생성 에러(ERROR org.apache.kafka.common.errors.InvalidReplicationFactorException: Replication factor: 1 larger than available brokers: 0) 

   해결 : zookeeper 리스트를 server.properties와 동일하게 맞춰줌, 지노드명까지

   출처 : https://twofootdog.tistory.com/94

2. - alter 이용해서 수정하기
     ![image-20230501013110178](C:\Users\뚜이\AppData\Roaming\Typora\typora-user-images\image-20230501013110178.png)

  - 삭제 후 재생성하기
    http://ngmsoftware.com/bbs/board.php?bo_table=study&wr_id=674&sfl=mb_id%2C1&stx=admin&sst=wr_nogood&sod=desc&sop=and&page=22

**Comment by seojeonghyeon** [comment]
https://github.com/seojeonghyeon/bankservice-userservice(com.zayden.bankserviceuserservice.kafka 내 producer)
https://docs.spring.io/spring-kafka/reference/html/#kafka-template

**Comment by kmg28801** [comment]
# Spring 기반 애플리케이션에서 도커 host 모르는 경우 해결방법
- mac
  - sudo vim /private/etc/hosts
  - 아래 URL을 참고하여, 본인 local PC의 host 파일 수정해준다.
- window
  - C:\Windows\System32\drivers\etc 경로의 hosts 파일
  - 아래 URL을 참고하여, 본인 local PC의 host 파일 수정해준다.
https://github.com/docker/for-win/issues/2402#issuecomment-411577799
